---

- name: setup common role
  hosts: bot
  user: root
  become: true
  pre_tasks:
    - name: preinstall packages
      apt:
        pkg: ['python3.7','python3-pip']
        update_cache: true
    - name: preinstall Python packages
      pip:
        name: vk_api
        executable: pip3